### ISSUE TITLE
Is this still working in 2023?

### ISSUE THREAD

**Issue by derrickrc** [Dan-Kouba/ble-wifi-setup-manager#2]
Hi Dan, I'm trying to play around with this and when I test on both Chrome (Android) and Bluefy (iOS) it's not returning any compatible devices. I have an Argon powered on advertising as a UART device. Is this still working or am I doing something wrong? Thanks.

**Comment by Dan-Kouba** [comment]
Hey Derrick! Would you mind starting a thread over in the [Particle Community](https://community.particle.io/)? If you can include the exact steps you have followed to get to where you are at, it would help a lot in debugging.

Feel free to tag me @Dan-Kouba
